rubric:
  possibleScore:
  - requirement: repo contains starter/hello.c that prints "hello, world"
    points: 5
  - requirement: BATS tests pass
    points: 5
  - requirement: quality of question answers in the questions.md file
    points: 5
  possibleExtraCreditScore:
  - requirement: Demonstrate that you used gdb to debug
    points: 5
  requirements:
  - description: submit a working hello world program
    criteria:
    - must compile and run without errors
    - must print "hello, world" to stdout
  - description: BATS test must pass
    criteria:
    - make test must pass without errors
  - description: optional extra credit that gdb was used to debug
    criteria:
    - submit an image file with a breakpoint set on line 5 (printf("Hello, World!\n");
    - the breakpoint must be the active line of code in a debug session
  - description: answer the questions in questions.md
    criteria:
    - must place each quesiton answer after the question in questions.md
    - must provide a complete, correct, and thorough answer



